### ISSUE TITLE
Bottom row deletion + table refresh

### ISSUE THREAD

**Issue by kameelyan** [PicNet/tablefilter#49] opened 2012-06-02 04:22 UTC
Ok, so I've come across an issue when you refresh the table after the bottom row has been deleted.

Essentially, I was doing the following:

$('table tr:last').remove();
$('table').tableFilterRefresh();

But an error was being generated in this function because "el" was undefined.
goog.style.isElementShown

So I just updated it to be to get it working, but thought you'd want to dive deeper.
goog.style.isElementShown = function (el) {
    if (el)
        return el.style.display != 'none';
};

**Comment by gatapia** [comment] 2012-09-02 00:13
I could not reproduce this using latest build, perhaps this was fixed in the closure libray since first reported.

**Closed as completed by gatapia** 2012-09-02 00:13 UTC
