### ISSUE TITLE
Enable cookies not selecting the current filter in ddl 

### ISSUE THREAD

**Issue by ghost** [PicNet/tablefilter#1] opened 2011-03-28 01:51 UTC
The problem I am having is this:
I select a filter from the ddl. It works fine. I go off the web page and then come back. The table is still filered but the selection in the ddl is still showing 'Select...' I am testing in both IE 8 and FF 3.6.13. Is this a bug or not supported? If not how can I implement it.
Thanks,
Joe

Let me further clarify that I am using two tables on one page. I did some further testing and got a postivie result on the first table.
I changed the 'selectOptionLable' option to something else on both tabels. The curent table filter selection now shows up in the ddl for the first table but not for the second table.

**Comment by henrikl** [comment] 2012-02-26 22:58
I can't reproduce this. I think this has probably been fixed (please test with the latest commit) so I'm closing this issue. If I'm wrong, write back or open a new issue.

**Closed as completed by henrikl** 2012-02-26 22:58 UTC
